global:
  resolve_timeout: 5m

route:
  receiver: webhook-local
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: webhook-local
    webhook_configs:
      - url: http://webmon-backend:3001/webhook/alerts
        send_resolved: true
